language: r

sudo: required

warnings_are_errors: false

env:
 global:
   - CRAN: http://cran.rstudio.com
   - r_build_args: --no-build-vignettes --no-manual
   - r_check_args: --no-build-vignettes --no-manual --as-cran

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel
